### PR TITLE
Fix error UnknownDomainObjectException with productFlavors

### PR DESCRIPTION
**Pull request by devnied**
**Error during build :**
AndroidSourceSet with name '' not found

This fix the issue #5

You can now use productFlavors in gradle.build, you must define the
**sourceSets** for all productFlavor if it does not match the default
one (src/$flavorname/java/)

``` groovy
android {
...
productFlavors {
pro {
…
}
free {
…
}
}

sourceSets {

free.java.srcDirs = ['src/test/java/']
free.resources.srcDirs = ['src/test/resources']
}
}
```

### CODE REVIEW

**Comment by stephanenicolas** [comment]
@devnied PR has been merged and refactored a bit. 

Can you try if it works for you ? If so, I will be pleased to publish a new version on central.
A snapshot is available for you to test. (version 1.0.12-SNAPSHOT)
(if you see I don't answer, find my email on gmail.com and ping me, I am on the move)

**Comment by devnied** [comment]
Yes, it works for me. Thanks

**Comment by mattcarron** [comment]
Hey @stephanenicolas , has this fix reached production as I am experiencing this issue with plugin version:
com.github.stephanenicolas.ormgap:ormgap-plugin:1.0.11

Many thanks,
Matt

**Comment by stephanenicolas** [comment]
@Matt Carron. Sorry but I don't remember. You should check at the state of
the code, release commits are tagged. Feel free to report here any issue
you find.

2016-11-11 13:33 GMT+02:00 Matt Carron notifications@github.com:

**Comment by mattcarron** [comment]
Hey @stephanenicolas so in the latest release (1.0.11) the changes in this PR are not there. 
See https://github.com/stephanenicolas/ormlite-android-gradle-plugin/blob/1.0.11/ormgap-plugin/src/main/groovy/com/github/stephanenicolas/ormgap/ORMGAPPlugin.groovy

Would it be possible to test these changes via a snapshot like you did before?

Thanks,
Matt

**Comment by stephanenicolas** [comment]
@jush @mattcarronflypay @devnied I am releasing the plugin 1.0.12. It should hit central today. Sorry to have been so laggy on this.

**Pull request merged**
